# Generated by Django 4.2 on 2023-04-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actual_price',
            field=models.IntegerField(),
        ),
    ]
