# Generated by Django 4.2 on 2023-04-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_order_actual_price_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_prise',
            new_name='total_price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='mainApp.order'),
        ),
    ]
