# Generated by Django 4.2 on 2023-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_phonenumber_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=b'688a928360d309501432996480edfe31d1326e402e7797d9d0656dabc2a91b72', max_length=64),
        ),
    ]
