# Generated by Django 4.2 on 2023-04-28 09:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{11,12}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=mainApp.models._create_token, max_length=64),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainApp.product')),
            ],
        ),
    ]
